# @package _global_

seed: 100                 # Seed number for random numbers.
f0_factors: [0.5,1.0,2.0]  # F0 factor.

data:
  # Dataset settings
  stats: configs/namine_ritsu_train_no_dev.joblib   # Path to the file of statistics.
  allow_cache: false  # Whether to allow cache in dataset. If true, it requires cpu memory

  # Feature settings
  sample_rate: 24000               # Sampling rate.
  hop_size: 120                    # Hop size.
  dense_factors: [ 0.5, 1, 4, 8 ]    # Dense factor in PDCNNs.
  sine_amp: 0.1                    # Sine amplitude.
  noise_amp: 0.003                 # Noise amplitude.
  signal_types: [ "sine" ]           # List of input signal types for generator.
  sine_f0_type: "cf0"              # F0 type for sine signal ("f0" or "cf0").
  df_f0_type: "cf0"                # F0 type for dilation factor ("f0" or "cf0").
  aux_feats: [ "mcep", "bap" ]       # Auxiliary features.
    # "uv": V/UV binary.
    # "f0": descrete f0.
    # "mcep": mel-cepstral envelope.
    # "cf0": continuous f0.
    # "mcap": mel-cepstral aperiodicity.
  # "bap": coded aperiodicity.
  # "logmsp": log mel-spectrogram.

  # Collater setting
  batch_max_length: 8400  # Length of each audio in batch. Make sure dividable by hop_size.

  # Data loader setting
  batch_size: 16     # Batch size
  num_workers: 1     # Number of workers in Pytorch DataLoader
  pin_memory: true   # Whether to pin memory in Pytorch DataLoader

  # Other setting
  remove_short_samples: true  # Whether to remove samples the length of which are less than batch_max_length

generator:
  upsample_scales: [5, 4, 3, 2]
